name: Testing
on:
  push:
    branches: main
    paths-ignore:
      - '.github/workflows/format.yml'
      - 'LICENSE'
      - 'README.md'
      - 'haxelib.json'
      - 'hxformat.json'
  workflow_dispatch:
jobs:
  Job:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        example: [models_heightmap]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Dependencies
        run: |
          haxelib install hxcpp --quiet
          haxelib dev raylib-hx .

      - name: Build Unix
        if: startsWith(matrix.os, 'ubuntu')
        run: cd examples/${{matrix.example}} && haxe build-unix.hxml

      - name: Build Windows
        if: startsWith(matrix.os, 'windows')
        run: cd examples/${{matrix.example}} && haxe build-win.hxml
